### ISSUE TITLE
Frequency how often audioStream:samplesAvailable is called

### ISSUE THREAD

**Issue by danielbuechele** [muhku/FreeStreamer#218] opened 2015-10-16 23:01 UTC
I basically used your sample project to play a stream of a radio station. I want to visualize the music played in a spectrum analyzer. So I implemented `FSFrequencyDomainAnalyzerDelegate`. However, the delegate callback is only called about 3 times a second which doesn't allow a smooth display. Is there a way to get more samples?

**Comment by sbpaul** [comment] 2015-10-17 00:40
i got the same problem. would love to see a fix too.

**Comment by Djelibeybi** [comment] 2015-10-25 17:31
Hey @danielbuechele - I was about to start looking at creating a spectrum analyser too. Any chance you can share your delete code?

**Comment by juanjoguevara** [comment] 2015-11-16 14:44
Same problem here.

**Comment by muhku** [comment] 2015-11-16 19:19
Currently you cannot get samples with a higher rate. This is because how the playback is internally implemented. Changing this would require:
1) Refactoring the audio converter out from Audio_Stream to its own class
2) Creating a pthread which runs the audio converter with a smaller buffer size and higher interval

This would benefit better memory utilization as we could lower the audio queue buffer sizes as well.

**Comment by gabek** [comment] 2015-11-23 19:21
+1!

**Comment by muhku** [comment] 2015-11-23 20:16
Some goods news for those who have been waiting: I pushed the changes into the lowlatency branch. The implementation is in commit 5d4f09ea1aa42a072823c3312fe1b82a2b6eed56

However, I am not ready yet to merge this into the mainline branch; the internals were shuffled quite a bit and there's some tricky locking related code and details which must be absolutely correct or things will go horribly wrong. This being said, the unit tests pass and I hope I ironed out most of the crashes.

If anybody is willing to try, please let me know how it goes with this :)

**Comment by muhku** [comment] 2015-11-24 14:39
Code pushed to master as well for easier testing.

**Comment by muhku** [comment] 2015-11-26 20:34
The latest version (3.0.0) in the master branch gives about 20 samples / second. I'm planning to release it eventually if no major regression bugs turn up. Let's close this one.

**Closed by muhku** 2015-11-26 20:34 UTC

**Comment by muhku** [comment] 2015-12-11 13:49
Hi. Those who are utilizing the new decoder, please use at least 3.0.11, which has some known issues fixed.
