### ISSUE TITLE
stream plays again from track's start after buffering

### ISSUE THREAD

**Issue by evkurganova** [muhku/FreeStreamer#275] opened 2016-04-13 08:30 UTC
@muhku I've problem.
I'm testing the stream with edge internet connections on FreeStreamer Example . The scenario:
Hit play, it buffers for a long period of time, which is understandable, and then (finally) it starts. It plays for a little time, 5 to 10 sec, and then it plays again from track's start.
At log: [audio_stream.cpp:781 thread c07] Audio queue run out data, starting buffering
Any light on this problem?

stream mp3: https://www.dropbox.com/s/wg9e8fcq1rywuh8/UMG_00602547161635_T8_audtrk.mp3?dl=1

**Comment by muhku** [comment] 2016-04-13 09:41
It sounds like the network bandwidth is not enough to provide sufficient throughput to keep the buffers filled. You can download Apple's [Network Link Conditioner](http://nshipster.com/network-link-conditioner/) to try out what is the minimal required bandwidth in your case.

**Comment by evkurganova** [comment] 2016-04-13 11:01
This problem occurs even if set _configuration.requiredPrebufferSizeInSeconds = 15: track reset to the beginning at cached area and doesn't updated duration. And even if the track was cached completely, problem occurs.
![screen shot 2016-04-13 at 15 59 05](https://cloud.githubusercontent.com/assets/10195755/14491167/b4050ff4-0190-11e6-8afd-aa9684fce21e.png)

**Comment by fibnochi** [comment] 2016-05-10 01:39
I am facing same issue for google drive links.

**Comment by dral3x** [comment] 2016-05-31 07:58
this issue is also reproducible if you cut down the network (turn off wifi for example) after the audio started. When the audio queue runs out of data to play, a new one is created with the old (already played content) and so the audio start over.

**Comment by RitvikM** [comment] 2016-06-10 09:22
@muhku any ideas on how to work around this issue? Is there a way to make the audio just pause and continue once the buffer is filled again? Atm restarting the stream from the start is not the ideal user experience.

**Comment by rickyjwhong** [comment] 2016-07-07 16:13
Hi, same thing is happening here. Tracks are restarting at random points

**Comment by muhku** [comment] 2016-08-16 17:05
I'm wondering if this happens because of the HTTP connection auto recovery: https://github.com/muhku/FreeStreamer/blob/master/FreeStreamer/FreeStreamer/http_stream.cpp#L772

Do you get the "Recovering HTTP stream, start" trace when this happens? This would be really useful information.

If the server doesn't support content range HTTP requests and a recovery is attempted, things will surely go wrong.

**Comment by muhku** [comment] 2016-08-16 17:06
If this is the case, I could add a configuration option for disabling auto recovery.

**Comment by seropusha** [comment] 2016-08-26 10:15
I do network connection to bad and test on "FreeStreamer example"
I see
[audio_stream.cpp:781 thread 70b] Audio queue run out data, starting buffering
states:
kFsAudioStreamBuffering 
and at once
kFsAudioStreamPlaying
and playing from start audio file without change position 

testing with my server(allow HTTP range), testing with amazon file, same.

https://github.com/muhku/FreeStreamer/blob/master/FreeStreamer/FreeStreamer/http_stream.cpp#L761

CFReadStreamGetStatus(stream) never isEqual to kCFStreamStatusError
and
bytes always > 0 

so does not set a new position 

maybe I do something wrong, please help

**Comment by muhku** [comment] 2016-08-26 14:58
Thanks for testing. So nothing to do with the auto recovery, then. Then it is likely so that in the buffering case the internal packet cache gets in a corrupt state. I was looking at this line:
https://github.com/muhku/FreeStreamer/blob/master/FreeStreamer/FreeStreamer/audio_stream.cpp#L775

It seems the line originally came from commit 88dc7e03c10523711b9afedc6ea78123b612edd3 (Issue #151)

**Comment by muhku** [comment] 2016-08-26 15:49
Does 151582b5527c508f98b62af150f18d5f0863575a make a difference?

**Comment by muhku** [comment] 2016-08-27 12:46
Commit 795a493d8d694a6d52a2b409234914661106418b should resume the playback pointer from the correct point. I hope this handles seeking as well. Closing and let me know if still more issues.

**Closed by muhku** 2016-08-27 12:46 UTC

**Comment by seropusha** [comment] 2016-09-07 10:13
Thanks for work, 

but now if stream haven't got bytes for playing, stream is stop,
 buffering, 
and after receive small bytes packets  At once playing, its no good because if low network connection we get small packet and At once continue playing and call

[audio_stream.cpp:802 thread c07] Audio queue run out data, starting buffering

many times, 

 Whether it is possible to do playing after get packets with requiredPrebufferSizePackets or requiredPrebufferSizeInSeconds?
